import collections

a = ['Brett Beer', ' Mixed-Fermentation Sour Beer', ' Wild Specialty Beer', ' Fruit Beer', 
' Fruit and Spice Beer', ' Specialty Fruit Beer', ' Spice', ' Herb', ' or Vegetable Beer', ' Alternative Grain Beer', ' Alternative Sugar Beer', ' Classic Style Smoked Beer', ' Specialty Smoked Beer', ' Wood-Aged Beer', ' Specialty Wood-Aged Beer', ' Clone Beer', ' Mixed-Style Beer', ' Experimental Beer', 
'Brett Beer', ' Mixed-Fermentation Sour Beer', ' Wild Specialty Beer', ' Fruit Beer', 
' Fruit and Spice Beer', ' Specialty Fruit Beer', ' Spice', ' Herb', ' or Vegetable Beer', ' Alternative Grain Beer', ' Alternative Sugar Beer', ' Classic Style Smoked Beer', ' Specialty Smoked Beer', ' Wood-Aged Beer', ' Specialty Wood-Aged Beer', ' Clone Beer', ' Mixed-Style Beer', ' Experimental Beer', 
'Brett Beer', ' Mixed-Fermentation Sour Beer', ' Wild Specialty Beer', ' Fruit Beer', 
' Fruit and Spice Beer', ' Specialty Fruit Beer', ' Spice', ' Herb', ' or Vegetable Beer', ' Alternative Grain Beer', ' Alternative Sugar Beer', ' Classic Style Smoked Beer', ' Specialty Smoked Beer', ' Wood-Aged Beer', ' Specialty Wood-Aged Beer', ' Clone Beer', ' Mixed-Style Beer', ' Experimental Beer', 
'Brett Beer', ' Mixed-Fermentation Sour Beer', ' Wild Specialty Beer', ' Fruit Beer', 
' Fruit and Spice Beer', ' Specialty Fruit Beer', ' Spice', ' Herb', ' or Vegetable Beer', ' Alternative Grain Beer', ' Alternative Sugar Beer', ' Classic Style Smoked Beer', ' Specialty Smoked Beer', ' Wood-Aged Beer', ' Specialty Wood-Aged Beer', ' Clone Beer', ' Mixed-Style Beer', ' Experimental Beer', 
'Brett Beer', ' Mixed-Fermentation Sour Beer', ' Wild Specialty Beer', ' Fruit Beer', 
' Fruit and Spice Beer', ' Specialty Fruit Beer', ' Spice', ' Herb', ' or Vegetable Beer', ' Alternative Grain Beer', ' Alternative Sugar Beer', ' Classic Style Smoked Beer', ' Specialty Smoked Beer', ' Wood-Aged Beer', ' Specialty Wood-Aged Beer', ' Clone Beer', ' Mixed-Style Beer', ' Experimental Beer', 
'Brett Beer', ' Mixed-Fermentation Sour Beer', ' Wild Specialty Beer', ' Fruit Beer', 
' Fruit and Spice Beer', ' Specialty Fruit Beer', ' Spice', ' Herb', ' or Vegetable Beer', ' Alternative Grain Beer', ' Alternative Sugar Beer', ' Classic Style Smoked Beer', ' Specialty Smoked Beer', ' Wood-Aged Beer', ' Specialty Wood-Aged Beer', ' Clone Beer', ' Mixed-Style Beer', ' Experimental Beer', 
'Brett Beer', ' Mixed-Fermentation Sour Beer', ' Wild Specialty Beer', ' Fruit Beer', 
' Fruit and Spice Beer', ' Specialty Fruit Beer', ' Spice', ' Herb', ' or Vegetable Beer', ' Alternative Grain Beer', ' Alternative Sugar Beer', ' Classic Style Smoked Beer', ' Specialty Smoked Beer', ' Wood-Aged Beer', ' Specialty Wood-Aged Beer', ' Clone Beer', ' Mixed-Style Beer', ' Experimental Beer', 
'Brett Beer', ' Mixed-Fermentation Sour Beer', ' Wild Specialty Beer', ' Fruit Beer', 
' Fruit and Spice Beer', ' Specialty Fruit Beer', ' Spice', ' Herb', ' or Vegetable Beer', ' Alternative Grain Beer', ' Alternative Sugar Beer', ' Classic Style Smoked Beer', ' Specialty Smoked Beer', ' Wood-Aged Beer', ' Specialty Wood-Aged Beer', ' Clone Beer', ' Mixed-Style Beer', ' Experimental Beer', 
'Brett Beer', ' Mixed-Fermentation Sour Beer', ' Wild Specialty Beer', ' Fruit Beer', 
' Fruit and Spice Beer', ' Specialty Fruit Beer', ' Spice', ' Herb', ' or Vegetable Beer', ' Alternative Grain Beer', ' Alternative Sugar Beer', ' Classic Style Smoked Beer', ' Specialty Smoked Beer', ' Wood-Aged Beer', ' Specialty Wood-Aged Beer', ' Clone Beer', ' Mixed-Style Beer', ' Experimental Beer', 
'Brett Beer', ' Mixed-Fermentation Sour Beer', ' Wild Specialty Beer', ' Fruit Beer', 
' Fruit and Spice Beer', ' Specialty Fruit Beer', ' Spice', ' Herb', ' or Vegetable Beer', ' Alternative Grain Beer', ' Alternative Sugar Beer', ' Classic Style Smoked Beer', ' Specialty Smoked Beer', ' Wood-Aged Beer', ' Specialty Wood-Aged Beer', ' Clone Beer', ' Mixed-Style Beer', ' Experimental Beer', 
'Brett Beer', ' Mixed-Fermentation Sour Beer', ' Wild Specialty Beer', ' Fruit Beer', 
' Fruit and Spice Beer', ' Specialty Fruit Beer', ' Spice', ' Herb', ' or Vegetable Beer', ' Alternative Grain Beer', ' Alternative Sugar Beer', ' Classic Style Smoked Beer', ' Specialty Smoked Beer', ' Wood-Aged Beer', ' Specialty Wood-Aged Beer', ' Clone Beer', ' Mixed-Style Beer', ' Experimental Beer', 
'Brett Beer', ' Mixed-Fermentation Sour Beer', ' Wild Specialty Beer', ' Fruit Beer', 
' Fruit and Spice Beer', ' Specialty Fruit Beer', ' Spice', ' Herb', ' or Vegetable Beer', ' Alternative Grain Beer', ' Alternative Sugar Beer', ' Classic Style Smoked Beer', ' Specialty Smoked Beer', ' Wood-Aged Beer', ' Specialty Wood-Aged Beer', ' Clone Beer', ' Mixed-Style Beer', ' Experimental Beer', 
'Brett Beer', ' Mixed-Fermentation Sour Beer', ' Wild Specialty Beer', ' Fruit Beer', 
' Fruit and Spice Beer', ' Specialty Fruit Beer', ' Spice', ' Herb', ' or Vegetable Beer', ' Alternative Grain Beer', ' Alternative Sugar Beer', ' Classic Style Smoked Beer', ' Specialty Smoked Beer', ' Wood-Aged Beer', ' Specialty Wood-Aged Beer', ' Clone Beer', ' Mixed-Style Beer', ' Experimental Beer', 
'Brett Beer', ' Mixed-Fermentation Sour Beer', ' Wild Specialty Beer', ' Fruit Beer', 
' Fruit and Spice Beer', ' Specialty Fruit Beer', ' Spice', ' Herb', ' or Vegetable Beer', ' Alternative Grain Beer', ' Alternative Sugar Beer', ' Classic Style Smoked Beer', ' Specialty Smoked Beer', ' Wood-Aged Beer', ' Specialty Wood-Aged Beer', ' Clone Beer', ' Mixed-Style Beer', ' Experimental Beer', 
'Brett Beer', ' Mixed-Fermentation Sour Beer', ' Wild Specialty Beer', ' Fruit Beer', 
' Fruit and Spice Beer', ' Specialty Fruit Beer', ' Spice', ' Herb', ' or Vegetable Beer', ' Alternative Grain Beer', ' Alternative Sugar Beer', ' Classic Style Smoked Beer', ' Specialty Smoked Beer', ' Wood-Aged Beer', ' Specialty Wood-Aged Beer', ' Clone Beer', ' Mixed-Style Beer', ' Experimental Beer', 
'Brett Beer', ' Mixed-Fermentation Sour Beer', ' Wild Specialty Beer', ' Fruit Beer', 
' Fruit and Spice Beer', ' Specialty Fruit Beer', ' Spice', ' Herb', ' or Vegetable Beer', ' Alternative Grain Beer', ' Alternative Sugar Beer', ' Classic Style Smoked Beer', ' Specialty Smoked Beer', ' Wood-Aged Beer', ' Specialty Wood-Aged Beer', ' Clone Beer', ' Mixed-Style Beer', ' Experimental Beer', 
'Brett Beer', ' Mixed-Fermentation Sour Beer', ' Wild Specialty Beer', ' Fruit Beer', 
' Fruit and Spice Beer', ' Specialty Fruit Beer', ' Spice', ' Herb', ' or Vegetable Beer', ' Alternative Grain Beer', ' Alternative Sugar Beer', ' Classic Style Smoked Beer', ' Specialty Smoked Beer', ' Wood-Aged Beer', ' Specialty Wood-Aged Beer', ' Clone Beer', ' Mixed-Style Beer', ' Experimental Beer', 
'Brett Beer', ' Mixed-Fermentation Sour Beer', ' Wild Specialty Beer', ' Fruit Beer', 
' Fruit and Spice Beer', ' Specialty Fruit Beer', ' Spice', ' Herb', ' or Vegetable Beer', ' Alternative Grain Beer', ' Alternative Sugar Beer', ' Classic Style Smoked Beer', ' Specialty Smoked Beer', ' Wood-Aged Beer', ' Specialty Wood-Aged Beer', ' Clone Beer', ' Mixed-Style Beer', ' Experimental Beer', 
'Brett Beer', ' Mixed-Fermentation Sour Beer', ' Wild Specialty Beer', ' Fruit Beer', 
' Fruit and Spice Beer', ' Specialty Fruit Beer', ' Spice', ' Herb', ' or Vegetable Beer', ' Alternative Grain Beer', ' Alternative Sugar Beer', ' Classic Style Smoked Beer', ' Specialty Smoked Beer', ' Wood-Aged Beer', ' Specialty Wood-Aged Beer', ' Clone Beer', ' Mixed-Style Beer', ' Experimental Beer', 
'Brett Beer', ' Mixed-Fermentation Sour Beer', ' Wild Specialty Beer', ' Fruit Beer', 
' Fruit and Spice Beer', ' Specialty Fruit Beer', ' Spice', ' Herb', ' or Vegetable Beer', ' Alternative Grain Beer', ' Alternative Sugar Beer', ' Classic Style Smoked Beer', ' Specialty Smoked Beer', ' Wood-Aged Beer', ' Specialty Wood-Aged Beer', ' Clone Beer', ' Mixed-Style Beer', ' Experimental Beer', 
'Brett Beer', ' Mixed-Fermentation Sour Beer', ' Wild Specialty Beer', ' Fruit Beer', 
' Fruit and Spice Beer', ' Specialty Fruit Beer', ' Spice', ' Herb', ' or Vegetable Beer', ' Alternative Grain Beer', ' Alternative Sugar Beer', ' Classic Style Smoked Beer', ' Specialty Smoked Beer', ' Wood-Aged Beer', ' Specialty Wood-Aged Beer', ' Clone Beer', ' Mixed-Style Beer', ' Experimental Beer', 
'Brett Beer', ' Mixed-Fermentation Sour Beer', ' Wild Specialty Beer', ' Fruit Beer', 
' Fruit and Spice Beer', ' Specialty Fruit Beer', ' Spice', ' Herb', ' or Vegetable Beer', ' Alternative Grain Beer', ' Alternative Sugar Beer', ' Classic Style Smoked Beer', ' Specialty Smoked Beer', ' Wood-Aged Beer', ' Specialty Wood-Aged Beer', ' Clone Beer', ' Mixed-Style Beer', ' Experimental Beer', 
'Brett Beer', ' Mixed-Fermentation Sour Beer', ' Wild Specialty Beer', ' Fruit Beer', 
' Fruit and Spice Beer', ' Specialty Fruit Beer', ' Spice', ' Herb', ' or Vegetable Beer', ' Alternative Grain Beer', ' Alternative Sugar Beer', ' Classic Style Smoked Beer', ' Specialty Smoked Beer', ' Wood-Aged Beer', ' Specialty Wood-Aged Beer', ' Clone Beer', ' Mixed-Style Beer', ' Experimental Beer', 
'Brett Beer', ' Mixed-Fermentation Sour Beer', ' Wild Specialty Beer', ' Fruit Beer', 
' Fruit and Spice Beer', ' Specialty Fruit Beer', ' Spice', ' Herb', ' or Vegetable Beer', ' Alternative Grain Beer', ' Alternative Sugar Beer', ' Classic Style Smoked Beer', ' Specialty Smoked Beer', ' Wood-Aged Beer', ' Specialty Wood-Aged Beer', ' Clone Beer', ' Mixed-Style Beer', ' Experimental Beer', 
'Brett Beer', ' Mixed-Fermentation Sour Beer', ' Wild Specialty Beer', ' Fruit Beer', 
' Fruit and Spice Beer', ' Specialty Fruit Beer', ' Spice', ' Herb', ' or Vegetable Beer', ' Alternative Grain Beer', ' Alternative Sugar Beer', ' Classic Style Smoked Beer', ' Specialty Smoked Beer', ' Wood-Aged Beer', ' Specialty Wood-Aged Beer', ' Clone Beer', ' Mixed-Style Beer', ' Experimental Beer', 
'Brett Beer', ' Mixed-Fermentation Sour Beer', ' Wild Specialty Beer', ' Fruit Beer', 
' Fruit and Spice Beer', ' Specialty Fruit Beer', ' Spice', ' Herb', ' or Vegetable Beer', ' Alternative Grain Beer', ' Alternative Sugar Beer', ' Classic Style Smoked Beer', ' Specialty Smoked Beer', ' Wood-Aged Beer', ' Specialty Wood-Aged Beer', ' Clone Beer', ' Mixed-Style Beer', ' Experimental Beer', 
'Brett Beer', ' Mixed-Fermentation Sour Beer', ' Wild Specialty Beer', ' Fruit Beer', 
' Fruit and Spice Beer', ' Specialty Fruit Beer', ' Spice', ' Herb', ' or Vegetable Beer', ' Alternative Grain Beer', ' Alternative Sugar Beer', ' Classic Style Smoked Beer', ' Specialty Smoked Beer', ' Wood-Aged Beer', ' Specialty Wood-Aged Beer', ' Clone Beer', ' Mixed-Style Beer', ' Experimental Beer', 
'Brett Beer', ' Mixed-Fermentation Sour Beer', ' Wild Specialty Beer', ' Fruit Beer', 
' Fruit and Spice Beer', ' Specialty Fruit Beer', ' Spice', ' Herb', ' or Vegetable Beer', ' Alternative Grain Beer', ' Alternative Sugar Beer', ' Classic Style Smoked Beer', ' Specialty Smoked Beer', ' Wood-Aged Beer', ' Specialty Wood-Aged Beer', ' Clone Beer', ' Mixed-Style Beer', ' Experimental Beer', 
'Brett Beer', ' Mixed-Fermentation Sour Beer', ' Wild Specialty Beer', ' Fruit Beer', 
' Fruit and Spice Beer', ' Specialty Fruit Beer', ' Spice', ' Herb', ' or Vegetable Beer', ' Alternative Grain Beer', ' Alternative Sugar Beer', ' Classic Style Smoked Beer', ' Specialty Smoked Beer', ' Wood-Aged Beer', ' Specialty Wood-Aged Beer', ' Clone Beer', ' Mixed-Style Beer', ' Experimental Beer', 
'Brett Beer', ' Mixed-Fermentation Sour Beer', ' Wild Specialty Beer', ' Fruit Beer', 
' Fruit and Spice Beer', ' Specialty Fruit Beer', ' Spice', ' Herb', ' or Vegetable Beer', ' Alternative Grain Beer', ' Alternative Sugar Beer', ' Classic Style Smoked Beer', ' Specialty Smoked Beer', ' Wood-Aged Beer', ' Specialty Wood-Aged Beer', ' Clone Beer', ' Mixed-Style Beer', ' Experimental Beer', 
'Brett Beer', ' Mixed-Fermentation Sour Beer', ' Wild Specialty Beer', ' Fruit Beer', 
' Fruit and Spice Beer', ' Specialty Fruit Beer', ' Spice', ' Herb', ' or Vegetable Beer', ' Alternative Grain Beer', ' Alternative Sugar Beer', ' Classic Style Smoked Beer', ' Specialty Smoked Beer', ' Wood-Aged Beer', ' Specialty Wood-Aged Beer', ' Clone Beer', ' Mixed-Style Beer', ' Experimental Beer', 
'Brett Beer', ' Mixed-Fermentation Sour Beer', ' Wild Specialty Beer', ' Fruit Beer', 
' Fruit and Spice Beer', ' Specialty Fruit Beer', ' Spice', ' Herb', ' or Vegetable Beer', ' Alternative Grain Beer', ' Alternative Sugar Beer', ' Classic Style Smoked Beer', ' Specialty Smoked Beer', ' Wood-Aged Beer', ' Specialty Wood-Aged Beer', ' Clone Beer', ' Mixed-Style Beer', ' Experimental Beer', 
'Brett Beer', ' Mixed-Fermentation Sour Beer', ' Wild Specialty Beer', ' Fruit Beer', 
' Fruit and Spice Beer', ' Specialty Fruit Beer', ' Spice', ' Herb', ' or Vegetable Beer', ' Alternative Grain Beer', ' Alternative Sugar Beer', ' Classic Style Smoked Beer', ' Specialty Smoked Beer', ' Wood-Aged Beer', ' Specialty Wood-Aged Beer', ' Clone Beer', ' Mixed-Style Beer', ' Experimental Beer', 
'Brett Beer', ' Mixed-Fermentation Sour Beer', ' Wild Specialty Beer', ' Fruit Beer', 
' Fruit and Spice Beer', ' Specialty Fruit Beer', ' Spice', ' Herb', ' or Vegetable Beer', ' Alternative Grain Beer', ' Alternative Sugar Beer', ' Classic Style Smoked Beer', ' Specialty Smoked Beer', ' Wood-Aged Beer', ' Specialty Wood-Aged Beer', ' Clone Beer', ' Mixed-Style Beer', ' Experimental Beer', 
'Brett Beer', ' Mixed-Fermentation Sour Beer', ' Wild Specialty Beer', ' Fruit Beer', 
' Fruit and Spice Beer', ' Specialty Fruit Beer', ' Spice', ' Herb', ' or Vegetable Beer', ' Alternative Grain Beer', ' Alternative Sugar Beer', ' Classic Style Smoked Beer', ' Specialty Smoked Beer', ' Wood-Aged Beer', ' Specialty Wood-Aged Beer', ' Clone Beer', ' Mixed-Style Beer', ' Experimental Beer', 
'Brett Beer', ' Mixed-Fermentation Sour Beer', ' Wild Specialty Beer', ' Fruit Beer', 
' Fruit and Spice Beer', ' Specialty Fruit Beer', ' Spice', ' Herb', ' or Vegetable Beer', ' Alternative Grain Beer', ' Alternative Sugar Beer', ' Classic Style Smoked Beer', ' Specialty Smoked Beer', ' Wood-Aged Beer', ' Specialty Wood-Aged Beer', ' Clone Beer', ' Mixed-Style Beer', ' Experimental Beer', 
'Brett Beer', ' Mixed-Fermentation Sour Beer', ' Wild Specialty Beer', ' Fruit Beer', 
' Fruit and Spice Beer', ' Specialty Fruit Beer', ' Spice', ' Herb', ' or Vegetable Beer', ' Alternative Grain Beer', ' Alternative Sugar Beer', ' Classic Style Smoked Beer', ' Specialty Smoked Beer', ' Wood-Aged Beer', ' Specialty Wood-Aged Beer', ' Clone Beer', ' Mixed-Style Beer', ' Experimental Beer', 
'Brett Beer', ' Mixed-Fermentation Sour Beer', ' Wild Specialty Beer', ' Fruit Beer', 
' Fruit and Spice Beer', ' Specialty Fruit Beer', ' Spice', ' Herb', ' or Vegetable Beer', ' Alternative Grain Beer', ' Alternative Sugar Beer', ' Classic Style Smoked Beer', ' Specialty Smoked Beer', ' Wood-Aged Beer', ' Specialty Wood-Aged Beer', ' Clone Beer', ' Mixed-Style Beer', ' Experimental Beer', 
'Brett Beer', ' Mixed-Fermentation Sour Beer', ' Wild Specialty Beer', ' Fruit Beer', 
' Fruit and Spice Beer', ' Specialty Fruit Beer', ' Spice', ' Herb', ' or Vegetable Beer', ' Alternative Grain Beer', ' Alternative Sugar Beer', ' Classic Style Smoked Beer', ' Specialty Smoked Beer', ' Wood-Aged Beer', ' Specialty Wood-Aged Beer', ' Clone Beer', ' Mixed-Style Beer', ' Experimental Beer', 
'Brett Beer', ' Mixed-Fermentation Sour Beer', ' Wild Specialty Beer', ' Fruit Beer', 
' Fruit and Spice Beer', ' Specialty Fruit Beer', ' Spice', ' Herb', ' or Vegetable Beer', ' Alternative Grain Beer', ' Alternative Sugar Beer', ' Classic Style Smoked Beer', ' Specialty Smoked Beer', ' Wood-Aged Beer', ' Specialty Wood-Aged Beer', ' Clone Beer', ' Mixed-Style Beer', ' Experimental Beer', 
'Brett Beer', ' Mixed-Fermentation Sour Beer', ' Wild Specialty Beer', ' Fruit Beer', 
' Fruit and Spice Beer', ' Specialty Fruit Beer', ' Spice', ' Herb', ' or Vegetable Beer', ' Alternative Grain Beer', ' Alternative Sugar Beer', ' Classic Style Smoked Beer', ' Specialty Smoked Beer', ' Wood-Aged Beer', ' Specialty Wood-Aged Beer', ' Clone Beer', ' Mixed-Style Beer', ' Experimental Beer', 
'Brett Beer', ' Mixed-Fermentation Sour Beer', ' Wild Specialty Beer', ' Fruit Beer', 
' Fruit and Spice Beer', ' Specialty Fruit Beer', ' Spice', ' Herb', ' or Vegetable Beer', ' Alternative Grain Beer', ' Alternative Sugar Beer', ' Classic Style Smoked Beer', ' Specialty Smoked Beer', ' Wood-Aged Beer', ' Specialty Wood-Aged Beer', ' Clone Beer', ' Mixed-Style Beer', ' Experimental Beer', 
'Brett Beer', ' Mixed-Fermentation Sour Beer', ' Wild Specialty Beer', ' Fruit Beer', 
' Fruit and Spice Beer', ' Specialty Fruit Beer', ' Spice', ' Herb', ' or Vegetable Beer', ' Alternative Grain Beer', ' Alternative Sugar Beer', ' Classic Style Smoked Beer', ' Specialty Smoked Beer', ' Wood-Aged Beer', ' Specialty Wood-Aged Beer', ' Clone Beer', ' Mixed-Style Beer', ' Experimental Beer', 
'Brett Beer', ' Mixed-Fermentation Sour Beer', ' Wild Specialty Beer', ' Fruit Beer', 
' Fruit and Spice Beer', ' Specialty Fruit Beer', ' Spice', ' Herb', ' or Vegetable Beer', ' Alternative Grain Beer', ' Alternative Sugar Beer', ' Classic Style Smoked Beer', ' Specialty Smoked Beer', ' Wood-Aged Beer', ' Specialty Wood-Aged Beer', ' Clone Beer', ' Mixed-Style Beer', ' Experimental Beer', 
'Brett Beer', ' Mixed-Fermentation Sour Beer', ' Wild Specialty Beer', ' Fruit Beer', 
' Fruit and Spice Beer', ' Specialty Fruit Beer', ' Spice', ' Herb', ' or Vegetable Beer', ' Alternative Grain Beer', ' Alternative Sugar Beer', ' Classic Style Smoked Beer', ' Specialty Smoked Beer', ' Wood-Aged Beer', ' Specialty Wood-Aged Beer', ' Clone Beer', ' Mixed-Style Beer', ' Experimental Beer', 
'Brett Beer', ' Mixed-Fermentation Sour Beer', ' Wild Specialty Beer', ' Fruit Beer', 
' Fruit and Spice Beer', ' Specialty Fruit Beer', ' Spice', ' Herb', ' or Vegetable Beer', ' Alternative Grain Beer', ' Alternative Sugar Beer', ' Classic Style Smoked Beer', ' Specialty Smoked Beer', ' Wood-Aged Beer', ' Specialty Wood-Aged Beer', ' Clone Beer', ' Mixed-Style Beer', ' Experimental Beer', 
'Brett Beer', ' Mixed-Fermentation Sour Beer', ' Wild Specialty Beer', ' Fruit Beer', 
' Fruit and Spice Beer', ' Specialty Fruit Beer', ' Spice', ' Herb', ' or Vegetable Beer', ' Alternative Grain Beer', ' Alternative Sugar Beer', ' Classic Style Smoked Beer', ' Specialty Smoked Beer', ' Wood-Aged Beer', ' Specialty Wood-Aged Beer', ' Clone Beer', ' Mixed-Style Beer', ' Experimental Beer', 
'Brett Beer', ' Mixed-Fermentation Sour Beer', ' Wild Specialty Beer', ' Fruit Beer', 
' Fruit and Spice Beer', ' Specialty Fruit Beer', ' Spice', ' Herb', ' or Vegetable Beer', ' Alternative Grain Beer', ' Alternative Sugar Beer', ' Classic Style Smoked Beer', ' Specialty Smoked Beer', ' Wood-Aged Beer', ' Specialty Wood-Aged Beer', ' Clone Beer', ' Mixed-Style Beer', ' Experimental Beer', 
'Brett Beer', ' Mixed-Fermentation Sour Beer', ' Wild Specialty Beer', ' Fruit Beer', 
' Fruit and Spice Beer', ' Specialty Fruit Beer', ' Spice', ' Herb', ' or Vegetable Beer', ' Alternative Grain Beer', ' Alternative Sugar Beer', ' Classic Style Smoked Beer', ' Specialty Smoked Beer', ' Wood-Aged Beer', ' Specialty Wood-Aged Beer', ' Clone Beer', ' Mixed-Style Beer', ' Experimental Beer', 
'Brett Beer', ' Mixed-Fermentation Sour Beer', ' Wild Specialty Beer', ' Fruit Beer', 
' Fruit and Spice Beer', ' Specialty Fruit Beer', ' Spice', ' Herb', ' or Vegetable Beer', ' Alternative Grain Beer', ' Alternative Sugar Beer', ' Classic Style Smoked Beer', ' Specialty Smoked Beer', ' Wood-Aged Beer', ' Specialty Wood-Aged Beer', ' Clone Beer', ' Mixed-Style Beer', ' Experimental Beer', 'Brett Beer', ' Mixed-Fermentation Sour Beer', ' Wild Specialty Beer', ' Fruit Beer', 
' Fruit and Spice Beer', ' Specialty Fruit Beer', ' Spice', ' Herb', ' or Vegetable Beer', ' Alternative Grain Beer', ' Alternative Sugar Beer', ' Classic Style Smoked Beer', ' Specialty Smoked Beer', ' Wood-Aged Beer', ' Specialty Wood-Aged Beer', ' Clone Beer', ' Mixed-Style Beer', ' Experimental Beer', 
'Brett Beer', ' Mixed-Fermentation Sour Beer', ' Wild Specialty Beer', ' Fruit Beer', 
' Fruit and Spice Beer', ' Specialty Fruit Beer', ' Spice', ' Herb', ' or Vegetable Beer', ' Alternative Grain Beer', ' Alternative Sugar Beer', ' Classic Style Smoked Beer', ' Specialty Smoked Beer', ' Wood-Aged Beer', ' Specialty Wood-Aged Beer', ' Clone Beer', ' Mixed-Style Beer', ' Experimental Beer', 
'Brett Beer', ' Mixed-Fermentation Sour Beer', ' Wild Specialty Beer', ' Fruit Beer', 
' Fruit and Spice Beer', ' Specialty Fruit Beer', ' Spice', ' Herb', ' or Vegetable Beer', ' Alternative Grain Beer', ' Alternative Sugar Beer', ' Classic Style Smoked Beer', ' Specialty Smoked Beer', ' Wood-Aged Beer', ' Specialty Wood-Aged Beer', ' Clone Beer', ' Mixed-Style Beer', ' Experimental Beer', 
'Brett Beer', ' Mixed-Fermentation Sour Beer', ' Wild Specialty Beer', ' Fruit Beer', 
' Fruit and Spice Beer', ' Specialty Fruit Beer', ' Spice', ' Herb', ' or Vegetable Beer', ' Alternative Grain Beer', ' Alternative Sugar Beer', ' Classic Style Smoked Beer', ' Specialty Smoked Beer', ' Wood-Aged Beer', ' Specialty Wood-Aged Beer', ' Clone Beer', ' Mixed-Style Beer', ' Experimental Beer', 
'Brett Beer', ' Mixed-Fermentation Sour Beer', ' Wild Specialty Beer', ' Fruit Beer', 
' Fruit and Spice Beer', ' Specialty Fruit Beer', ' Spice', ' Herb', ' or Vegetable Beer', ' Alternative Grain Beer', ' Alternative Sugar Beer', ' Classic Style Smoked Beer', ' Specialty Smoked Beer', ' Wood-Aged Beer', ' Specialty Wood-Aged Beer', ' Clone Beer', ' Mixed-Style Beer', ' Experimental Beer', 
'Brett Beer', ' Mixed-Fermentation Sour Beer', ' Wild Specialty Beer', ' Fruit Beer', 
' Fruit and Spice Beer', ' Specialty Fruit Beer', ' Spice', ' Herb', ' or Vegetable Beer', ' Alternative Grain Beer', ' Alternative Sugar Beer', ' Classic Style Smoked Beer', ' Specialty Smoked Beer', ' Wood-Aged Beer', ' Specialty Wood-Aged Beer', ' Clone Beer', ' Mixed-Style Beer', ' Experimental Beer', 
'Brett Beer', ' Mixed-Fermentation Sour Beer', ' Wild Specialty Beer', ' Fruit Beer', 
' Fruit and Spice Beer', ' Specialty Fruit Beer', ' Spice', ' Herb', ' or Vegetable Beer', ' Alternative Grain Beer', ' Alternative Sugar Beer', ' Classic Style Smoked Beer', ' Specialty Smoked Beer', ' Wood-Aged Beer', ' Specialty Wood-Aged Beer', ' Clone Beer', ' Mixed-Style Beer', ' Experimental Beer', ]
counter = collections.Counter(a)

# print(counter)
# Counter({1: 4, 2: 4, 3: 2, 5: 2, 4: 1})
# print(counter.values())
# [4, 4, 2, 1, 2]
print(counter.keys())
# [1, 2, 3, 4, 5]
# print(counter.most_common(3))
# [(1, 4), (2, 4), (3, 2)]